### ISSUE TITLE
Use userAwareMeta.getQuerySettings(query).getMaxRecordsPerPage() instead 'defaultPageLimit'

### ISSUE THREAD

**Issue by QProgS** [DevelopmentOnTheEdge/be5#17]
use
```
settings:
- settings:
    maxRecordsPerPage: 100
    roles: [Administrator]
```
instead
`layout: '{"defaultPageLimit": 100}'`
