### ISSUE TITLE
JavaScript operations

### ISSUE THREAD

**Issue by QProgS** [DevelopmentOnTheEdge/be5#54]
Сейчас в yaml выглядит так, на фронтенде никак не обрабатывается
```
  - Print:
      type: JavaScript
      roles: Annotator
      code: '{ "action": "test", "args": [] }'
```
